servlet:
  context-path: /
  encoding:
    charset: UTF-8
    enabled: true
    force: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study/gameLibrary;
    username : sa
    password :
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        show_sql: true
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

