servlet:
  context-path: /
  encoding:
    charset: UTF-8
    enabled: true
    force: true
  multipart:
    maxFileSize: 10MB
    maxRequestSize : 20MB

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study/gameLibrary;
    username : sa
    password :
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        show_sql: true
      format_sql: true

  security:
   oauth2:
    client:
      registration:
        google:
          client-id: 157230314822-oh799k0dcm3htc9kd58793es3os3tg26.apps.googleusercontent.com
          client-secret: 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
          scope:
          - email
          - profile
  profile:
    include: google



logging:
  level:
    org.hibernate.SQL: debug


upload:
  path: C:/study/file/
